# Generated by Django 6.1 on 2026-09-19 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_users', '0001_initial'),
        ('tenants', '0005_rename_subdomain_tenant_tenant_subdomain'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TenantUsers',
            new_name='TenantUser',
        ),
    ]
