# Generated by Django 6.1 on 2026-09-20 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_users', '0002_rename_tenantusers_tenantuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantUserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='tenant_users.tenantuser')),
            ],
        ),
    ]
