# Generated by Django 6.0 on 2026-01-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
