# Generated by Django 6.0 on 2026-01-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='name',
            new_name='tenant_name',
        ),
        migrations.AddField(
            model_name='tenant',
            name='subdomain',
            field=models.CharField(default='default', max_length=100, unique=True),
        ),
    ]
