# Generated by Django 6.1 on 2026-09-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='subdomain',
            new_name='tenant_subdomain',
        ),
    ]
